### ISSUE TITLE
Create login button on analytics homepage

### ISSUE THREAD

**Issue by LoganHollins** [bcjobs/analytics-dashboard#66] opened 2016-04-15 17:44 UTC
Ryan would like a login button designed for the analytics homepage.

CC: @ryanstgermaine

**Comment by johnnyoshika** [comment] 2016-04-22 19:18
Closing as it's a duplicate of https://github.com/bcjobs/analytics/issues/207

**Closed as completed by johnnyoshika** 2016-04-22 19:18 UTC
