### ISSUE TITLE
Phase 3 Requirements

### ISSUE THREAD

**Issue by ryanstgermaine** [bcjobs/analytics-dashboard#59] opened 2016-04-01 23:08 UTC
**QA Process**
- Make sure we're receiving raw data
- What are the daily fluctuations in job number count

**New feature releases**
Only viewable to super user

**Build additional reports**
- Job Titles: Show top skills and companies specific to the "top job titles by open jobs" accessible by clicking on a top title
- Skills: Show top job titles and companies specific to the "top skills by open jobs" accessible by clicking on a top skill
- Companies: Show top skills and job titles specific to the "top companies by open jobs" accessible by clicking on a top company

These should be accessible by clicking the top titles, skills and companies in the main reports for [Software Jobs](http://analytics.bcjobs.ca/) and [IT-Jobs](http://analytics.bcjobs.ca/it-jobs)

For each report add a comparative line chart graph that shows the number of open jobs per quarter for that title, report or company showing the previous 4 quarters.

**Example:**
![capture](https://cloud.githubusercontent.com/assets/6778782/14222881/688c140a-f82b-11e5-8e96-bb04fb2b230e.PNG)

**Using SOVREN, can we extract:**
- Seniority levels - Junior, Intermediate, Senior
- Job Type - Full time, Part time, Temp...

If yes, let's look at adding pie charts for these attributes. If there are many that are unknown, we should include that in the pie chart.

**Raw Data**
- Restructure database to allow us to accept a second set of raw data that isn't deduplicated by BOTCODE. This second set will not be reported on in the current dashboard reports.
- Restructure scraping process to send a second set of raw data
- Start importing raw data consistently from BOTCODE

**Replace Trending Job Titles Daily and Trending Skills Daily**
Delete these two reports and replace them with new reports that show Trending Job Titles and Trending Skills "All Time". These reports should include the numbers for all jobs ever recorded by our system.

**Create company Profiles and add these fields:**

**Industry** This will be a broader industry list that categorizes companies. Initially it will only contain two industries - "Technology" and "Other". Eventually we will add more industries so this should be supported from the beginning.

**Sub-Sectors**: Under the industries, we will have a sub-sector list. Initially this will just be for technology and the sub-sectors will include: Cleantech, biotech, lifesciences, engineering and ICT. Eventually all industries will have a sub-sector section so this should be supported from the beginning.

**Associations:**
Add a field to associate companies in our database with local associations.
- BC Technology Industry Association - 600 members
- HR Tech Group - 100 members
- VIATEC
- Accelerate Okanogan
- Lifesciences BC
- Digital media BC

For the industry, sub-sector and association fields, we should be able to import a .csv list of companies with industry, sub-sector and association columns and have the system map them to companies in our database using a fuzzy match.

For the associations, the goal will be for them to send us updated lists regularly so we can add and remove members as they become new members of cease to be members.

**Technology Industry Companies Reports**
Build reports for companies classified as being in the technology industry that shows all jobs by those companies including technical and non-technical roles. Report layout should be the same as our existing reports. #

**Comment by johnnyoshika** [comment] 2016-05-03 16:07
Duplicate of: https://github.com/bcjobs/analytics/issues/171

**Closed as completed by johnnyoshika** 2016-05-03 16:07 UTC
